#!/usr/bin/env bash

# Function to display information about a subdomain
display_info() {
    local sub_domain=$1
    local domain=$2
    local record_type=$(dig "$sub_domain.$domain" +short | awk '{print toupper($1)}')
    local destination=$(dig "$sub_domain.$domain" +short)

    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

# Main script
main() {
    local domain=$1
    local sub_domain=$2

    if [ -z "$sub_domain" ]; then
        # Display information for default subdomains
        display_info "www" "$domain"
        display_info "lb-01" "$domain"
        display_info "web-01" "$domain"
        display_info "web-02" "$domain"
    else
        # Display information for the specified subdomain
        display_info "$sub_domain" "$domain"
    fi
}

# Check if the correct number of arguments is provided
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

# Execute the main script
main "$1" "$2"
