#!/usr/bin/env bash
# check info about school file
n=school
if [ -e "$n" ]; then
	echo "school file exists";
	if [ -s "$n" ];
	then
		echo "school file is not empty";
	else
		echo "school file is empty";
	fi
	if [ -f "$n" ];
	then
		echo "school is a regular file";
	fi
else
	echo "school file does not exist";
fi
