#!/usr/bin/env bash
# check info about school file
# Check if the file school exists
if [ -e school ]; then
  echo "school file exists"
else
  echo "school file does not exist"
  exit 1 # Exit the script if the file does not exist
fi

# Check if the file school is empty
if [ -s school ]; then
  echo "school file is not empty"
else
  echo "school file is empty"
fi

# Check if the file school is a regular file
if [ -f school ]; then
  echo "school is a regular file"
fi
