#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "22 a\      add_header X-Served-By $(hostname);" /etc/nginx/nginx.conf
sudo service nginx restart
