#!/usr/bin/env bash
# Display "Best School" 10 times with "Hi" on the 9th iteration using a counter
counter=1
while [ $counter -le 10 ]; do
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done