#!/usr/bin/env bash
# Displays the time for 7 hours

hour=0
minute=1

while [ $hour -le 7 ]; do
    echo "Hour: $hour"
    while [ $minute -le 59 ]; do
        echo "$minute"
        ((minute++))
    done
    ((hour++))
    minute=1  # Reset minutes to 1 for the next hour
done
