#!/usr/bin/env bash
#displays the time for 7 hours
hour=0
minute=1
while [ $hour -le 7 ] && [ $minute -le 59 ]; do

    echo "Hour: $hour"
    while [ $minute -le 59 ]; do
        echo "$minute"
        ((minute++))
    done
    ((hour++))
    minute=1
done
